# Generated by Django 6.0.7 on 2026-08-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_options_alter_blogs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='short_desctiption',
            new_name='short_description',
        ),
    ]
